"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var rls = require("readline-sync");
var arregloMes = new Array(12);
arregloMes[0] = "Enero";
arregloMes[1] = "Febrero";
arregloMes[2] = "Marzo";
arregloMes[3] = "Abril";
arregloMes[4] = "Mayo";
arregloMes[5] = "Junio";
arregloMes[6] = "Julio";
arregloMes[7] = "Agosto";
arregloMes[8] = "Septiembre";
arregloMes[9] = "octubre";
arregloMes[10] = "Noviembre";
arregloMes[11] = "Diciembre";
var nroMes = rls.questionInt("Indique el numero de mes que le interesa: ");
var indice = nroMes - 1;
console.log("El mes es ", arregloMes[indice]);
